---
title: "Reply to Cabral et al. 2020 RAM BAU Policy"
author: 
  - Dan Ovando
  - Owen Liu
  - Renato Molina
  - Cody Szuwalski
date: "`r Sys.Date()`"
output: bookdown::pdf_document2
linkcolor: blue
toc: false
---

Letters to the Editor provide brief comments that allow readers to constructively address a difference of opinion with authors of a PNAS article.

- Letters are limited to 500 words and 10 references.

- Letters may not include requests to cite the Letter writer's work, accusations of misconduct, or personal comments to an author.

- Letters must be submitted within 6 months of the first online publication date of the subject article.

We strongly agree with three broad points raised by @cabral2020: 1) Marine Protected Areas (MPAs) have an important role play in global conservation and food security 2) Given the relative unproductivity of pelagic ecosystems [citation], a large percentage of the global oceans could be closed to fishing without substantially reducing global catch and 3) much of the food-security benefits of MPAs could be achieved by targeted protection in a few key places. However, we have serious concerns about the specific amounts of food benefits and priority locations for protection which are the core results of @cabral2020. Specifically there is an error in their business-as-usual (BAU) policy that if corrected produces meaningfully different results. Beyond this error, their model makes a series of highly questionable assumptions that produce a series of results inconsistent with best available knowledge of the state of global fisheries. 

@cabral2020's BAU model purports to follow the BAU policy described in @costello2016. Under this policy, equilibrium fishing pressure for a given fish stock is a function of its management institutions. Under the @costello2016 BAU policy, fisheries in the RAM Legacy Stock Assessment Database, which collectively make up roughly 50% of global marine captures, are assumed to maintain their current $F/F_{msy}$ (fishing mortality rate (*F*) relative to the fishing mortality rate that would produce maximum sustainable yield (*F~MSY~*))
"because they are neither poorly managed nor necessarily optimally managed [@cabral2020]". However, rather than using the most recent $F/F_{msy}$ from RAM for their BAU policy, @cabral2020 uses the most recent $F$ values. This is a critical difference, as they pair these $F$ values with a different $F_{msy}$ value than used in the RAM assessment. The net result of this is that @cabral2020 projects a future for RAM stocks totally inconsistent with their current management regimes. Under the BAU policy used in @costello2016, the median global $B/B_{msy}$ of RAM fisheries is XX. Under the @cabral2020 BAU, that value is only XX. The result of this error is a) to overestimate the potential food benefits from global MPAs by XX% and B) a map prioritizing MPAs in areas that have, under the assumptions of @costello2016 on which @cabral2020 is based, well managed fisheries that we would not expect to obtain food benefits from MPAs (Fig.\@ref(fig:XX)). Correcting this error produces a very different global network of marine protected areas for food. 

Fig.1: map of world with their BAU and the correct one, with global upsides in the panel titles.

```{r ram-bau-error}
# map of world with their BAU
```

This BAU error is relatively easy to correct, and should be accurately reflect the methods used in @costello2016 and our understanding of RAM stocks. However even with the correct BAU we do not feel that @cabral2020's model is capable of providing an accurate picture of a global MPA network for food provision. @cabral2020's model assumes that all unassessed stocks are part of one connected global population, with stock status and fishing mortality identical in ever fished patch. The result of this assumption is that their model assumes that MPAs placed in Australia can provide equal benefits to areas off of Indonesia and Baja California (Fig.XX-A), or that closures in the Caribbean can provide substantial benefits to species only caught near China (Fig.XX-B). A reader taking these results at face value then must be comfortable with a number of highly questionable results, such as that a food maximizing MPA network would close 40%XX of the USA to fishing, while placing no MPAs in India's EEZ, and only 10%-15% of Indonesia and China's EEZs in MPAs, despite @costello2016 estimating that these areas had XX times more to gain in terms of food security from reducing overfishing. 


Fig.2 - so many things... the Australia example + the china example? I guess that works since the first map shows people the percent closed in each EEZ.


We acknowledge that any model attempting to make globl inferences must make simplifying assumptions. However, the assumptions made in @cabral2020 are not neccesary. Beyond fixing the error in their BAU policy, a global model of MPAs should either constrain the range of individual populations to reflect the biological constraints of fish and larval movement and areas of consistent fishery institutions (following the same stock structure as @costello2016 would be a start in this direction), or explicitly model the role that distances play in ecological and economic responses to MPAs. 



